`TestDefinition/go_root/definition-goroot-a.go:1:40`: fix test
```sh
$ go test ./...
...
--- FAIL: TestDefinition (0.01s)
    --- FAIL: TestDefinition/go_root (0.00s)
        --- FAIL: TestDefinition/go_root/definition-goroot-a.go:1:40 (0.00s)
            lsp_definition_test.go:126:
                goroot/a.go:1:40
                got "/usr/local/go/src/fmt/print.go:274:6-274:13",
                want "/usr/local/go/src/fmt/print.go:263:6-263:13"
...
```

It should be `274:6-274:13`, proof:

```sh
$ grep -n 'Println' /usr/local/go/src/fmt/print.go
265:	p.doPrintln(a)
271:// Println formats using the default formats for its operands and writes to standard output.
274:func Println(a ...interface{}) (n int, err error) {
282:	p.doPrintln(a)
599:		// Println etc. set verb to %v, which is "stringable".
1152:// doPrintln is like doPrint but always adds a space between arguments
1154:func (p *pp) doPrintln(a []interface{}) {
```

```sh
$ sed -n 274p /usr/local/go/src/fmt/print.go
func Println(a ...interface{}) (n int, err error) {
```