`TestXDefinition/go_root/xdefinition-goroot-a.go:1:40`: fix test
```sh
$ go test ./...
...
--- FAIL: TestXDefinition (0.01s)
    --- FAIL: TestXDefinition/go_root (0.00s)
        --- FAIL: TestXDefinition/go_root/xdefinition-goroot-a.go:1:40 (0.00s)
            lsp_xdefinition_test.go:100:
                got  "/usr/local/go/src/fmt/print.go:274:6 id:fmt/-/Println name:Println package:fmt packageName:fmt recv: vendor:false"
                want "/usr/local/go/src/fmt/print.go:263:6 id:fmt/-/Println name:Println package:fmt packageName:fmt recv: vendor:false"
...
```

It should be `/usr/local/go/src/fmt/print.go:274:6...`, proof:

```sh
$ grep -n 'Println' /usr/local/go/src/fmt/print.go
265:	p.doPrintln(a)
271:// Println formats using the default formats for its operands and writes to standard output.
274:func Println(a ...interface{}) (n int, err error) {
282:	p.doPrintln(a)
599:		// Println etc. set verb to %v, which is "stringable".
1152:// doPrintln is like doPrint but always adds a space between arguments
1154:func (p *pp) doPrintln(a []interface{}) {
```

```sh
$ sed -n 274p /usr/local/go/src/fmt/print.go
func Println(a ...interface{}) (n int, err error) {
```